[package]
name = "bw_dat"
version = "0.1.0"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]

[dependencies]
libc = "0.2"

[dependencies.whack]
git = "https://github.com/neivv/whack/"
rev = "ccd95f5cfa37622bc3ec3d4b0974ab9b631b59b2"
